#!/usr/bin/python3

# Copyright 2019 Kamesh Raghavendra
# All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# File: factorise
# Description: Sample wrapper program for prifpy from command line

import prifpy
import sys

try:
	cmd = str(sys.argv[1])
except:
	print(prifpy.ERRORCOLOR + "[ERROR] Wrong command chosen.\n" + prifpy.LOSECOLOR + "Usage: prifpy-cmd primefac | lcm | hcf <number(s)>\n")
	sys.exit()

if cmd == "primefac":
	try:
		num = int(sys.argv[2])
	except:
		print(prifpy.ERRORCOLOR + "[ERROR] Wrong prime facterization input '" + str(num) + "'. Please try again with an integer number greater than zero.\n" + prifpy.LOSECOLOR)
		sys.exit()

	if num < 1:
		print(prifpy.ERRORCOLOR + "[ERROR] Wrong prime facterization input '" + str(num) + "'. Please try again with an integer number greater than zero.\n" + prifpy.LOSECOLOR)
		sys.exit()
	else:
		prifpy.printprifac(prifpy.prifac(num))

elif cmd == "lcm":
	numbers = []
	try:
		for number in sys.argv[2:]:
			numbers.append(int(number))
	except:
		print(prifpy.ERRORCOLOR + "[ERROR] Ill formed list of numbers for LCM. Please separate the numbers with spaces.\n" + prifpy.LOSECOLOR)
		sys.exit()
	lcm = prifpy.lcm(numbers)
	print("The LCM of the numbers " + str(numbers) + " is " + str(lcm[-1]) + " with the following prime factorization:")
	prifpy.printprifac(lcm)

elif cmd == "hcf":
	numbers = []
	try:
		for number in sys.argv[2:]:
			numbers.append(int(number))
	except:
		print(prifpy.ERRORCOLOR + "[ERROR] Ill formed list of numbers for LCM. Please separate the numbers with spaces.\n" + prifpy.LOSECOLOR)
		sys.exit()
	hcf = prifpy.hcf(numbers)
	print("The LCM of the numbers " + str(numbers) + " is " + str(hcf[-1]) + " with the following prime factorization:")
	prifpy.printprifac(hcf)

else:
	print("Welcome to prifpy-cmd; the command line wrapper for prifpy module for prime factorization.\nUsage: prifpy-cmd primefac | lcm | hcf <number(s)>\n")
